2022-03-17 09:03:53,113 ERROR: Exception on /exitdevice [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\app\frontend\views.py", line 64, in exit_device
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-03-31 14:10:18,166 ERROR: Exception on / [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Проекты\GKB3\webqueue2\app\frontend\views.py", line 14, in main
    return render_template('home.html', current_user=current_user)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Проекты\GKB3\webqueue2\app\templates\home.html", line 14, in <module>
    {% ifelse current_user.has_role('operator') %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'ifelse'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-03-31 15:11:58,834 ERROR: Exception on /logout [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Проекты\GKB3\webqueue2\app\auth\views.py", line 32, in logout
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-03-31 15:30:09,654 ERROR: Exception on /logout [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Проекты\GKB3\webqueue2\app\auth\views.py", line 32, in logout
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-04-02 13:23:49,718 ERROR: Exception on /logout [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Проекты\GKB3\webqueue2\app\auth\views.py", line 32, in logout
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-04-02 13:42:54,578 ERROR: Exception on /exitdevice [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\app\frontend\views.py", line 63, in exit_device
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-04-02 13:42:57,842 ERROR: Exception on /exitdevice [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\app\frontend\views.py", line 63, in exit_device
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
2022-04-02 13:43:04,421 ERROR: Exception on /logout [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Проекты\GKB3\webqueue2\app\auth\views.py", line 32, in logout
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
