2022-03-17 09:03:53,113 ERROR: Exception on /exitdevice [GET] [in D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Проекты\GKB3\webqueue2\app\frontend\views.py", line 64, in exit_device
    session.pop("location")
  File "D:\Проекты\GKB3\webqueue2\venv\lib\site-packages\werkzeug\datastructures.py", line 218, in pop
    rv = super().pop(key)
KeyError: 'location'
